### PR TITLE
Add grouping filters for "and" and "or".

### PR DESCRIPTION
**Pull request by manthey**
Update the documentation in the README.

### CODE REVIEW

**Comment by manthey** [comment]
@matthewma7 and @dorukozturk, this adds grouping filters (see the updated README).  I need to add tests before this should be reviewed.  The SQL grouping filters have worked in my limited testing.

**Comment by matthewma7** [comment]
Thank you @manthey, this is great. 👍 I am trying it out.

**Comment by manthey** [comment]
@matthewma7 If this meets your needs, then it is ready for review.

**Comment by matthewma7** [comment]
@manthey, Thank you for this great feature. I did some manual tests and reviewed the code. It LGTM.

**Pull request merged**
