### PR TITLE
Add group options.

### PR DESCRIPTION
**Pull request by manthey**
This is the GROUP BY sql parameter and is added for all SQL variants.  It has not been added for Mongo.

### CODE REVIEW

**Comment by manthey** [comment]
This finishes addressing issue #27.

**Comment by matthewma7** [comment]
@manthey, Thank you for this PR, the feature worked great for me. 👍 

One small thing, I don't know if we want to add a test that passes a JSON array or serialized JSON array string the **group**, which is already supported.

**Comment by aashish24** [comment]
@manthey is this ready to be merged? Looks like @matthewma7 reviewed it.

**Comment by manthey** [comment]
@matthewma7 asked for more tests.  I added some.  He should approve or ask for additional changes.

**Comment by matthewma7** [comment]
@manthey, The new example looks great. The functionality has been working great for me.

**Pull request merged**
